import type { Metadata } from 'next';
import { PasteScreen } from '@/components/paste/paste-screen';
import { PasteErrorState } from '@/components/paste/paste-error';
import { AppError } from '@/lib/errors';
import { getPasteMetadata, readPasteContent } from '@/lib/paste/service';
import { site } from '@/lib/config/site';
import type { PasteContent, PasteMetadata } from '@/types/paste';

// Paste pages are per-request and must never be cached or prerendered.
export const dynamic = 'force-dynamic';
export const revalidate = 0;

/**
 * Generic metadata only.
 *
 * Titles and content are deliberately kept out of <meta> tags: a link preview
 * generated by a chat client would otherwise leak a private paste's contents to
 * a third-party crawler. Paste pages are also noindex — privacy wins over SEO.
 */
export const metadata: Metadata = {
  title: 'Paste',
  description: `A paste on ${site.name}.`,
  robots: { index: false, follow: false, nocache: true },
};

type PageProps = {
  params: Promise<{ slug: string }>;
  searchParams: Promise<Record<string, string | string[] | undefined>>;
};

export default async function PastePage({ params, searchParams }: PageProps) {
  const { slug } = await params;
  const query = await searchParams;
  const created = query.created === '1';

  let meta: PasteMetadata;
  try {
    meta = await getPasteMetadata(slug);
  } catch (error) {
    return <PasteErrorState code={error instanceof AppError ? error.code : 'INTERNAL_ERROR'} slug={slug} />;
  }

  // Password and burn pastes are gated: nothing but metadata is rendered until
  // the visitor proves they should see the body.
  if (meta.isPasswordProtected) {
    return <PasteScreen meta={meta} initialBody={null} gate="password" created={created} />;
  }
  if (meta.burnAfterRead) {
    return <PasteScreen meta={meta} initialBody={null} gate="burn" created={created} />;
  }

  let body: PasteContent;
  let resolvedMeta = meta;
  try {
    // The creator's own post-creation redirect is not counted as a view.
    const payload = await readPasteContent(slug, { countView: !created });
    body = payload.body;
    resolvedMeta = payload.meta;
  } catch (error) {
    return <PasteErrorState code={error instanceof AppError ? error.code : 'INTERNAL_ERROR'} slug={slug} />;
  }

  return <PasteScreen meta={resolvedMeta} initialBody={body} gate="none" created={created} />;
}
